#!/usr/bin/env bash

options="   lock\n   suspend\n   logout\n   reboot\n   shutdown"

selected=$(echo -e "$options" | rofi \
  -theme-str 'window { width: 250px; height:280px; } inputbar { children: [entry]; } entry {margin: 20px 20px 0px 20px;}' \
  -dmenu -i \
  -lines 5 \
  -line-margin 5 \
  -line-padding 5 \
  -kb-row-tab '')

case $selected in
  *lock)
    betterlockscreen -l dim
    ;;
  *suspend)
    systemctl suspend
    ;;
  *logout)
    i3-msg exit
    ;;
  *reboot)
    systemctl reboot
    ;;
  *shutdown)
    systemctl poweroff
    ;;
esac
