# ~/.bash_profile
# Executed by bash(1) for login shells.

# If ~/.profile exists, source it
if [ -f ~/.profile ]; then
  . ~/.profile
fi

# If ~/.bashrc exists, source it
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

