services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - proxynet
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs/${TAILSCALE_URL}.crt:/etc/ssl/certs/tailscale.crt:ro
      - ./nginx/certs/${TAILSCALE_URL}.key:/etc/ssl/private/tailscale.key:ro
    environment:
      TAILSCALE_NAME: ${TAILSCALE_NAME}
      TAILSCALE_IP: ${TAILSCALE_IP}
      TAILSCALE_URL: ${TAILSCALE_URL}

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - proxynet
    environment:
      DOMAIN: "https://${TAILSCALE_URL}/vw"
      SIGNUPS_ALLOWED: "false"
      # ADMIN_TOKEN: ""
    volumes:
      - vaultwarden-data:/data/

  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri  # hardware acceleration
    entrypoint: ["/entrypoint.sh"]
    environment:
      - JELLYFIN_PublishedServerUrl=http://lisan-al-gaib/jellyfin
    image: jellyfin/jellyfin:latest
    networks:
      - proxynet
    ports:
      - "8096:8096"
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - jellyfin-data:/config
      - ./jellyfin/entrypoint.sh:/entrypoint.sh
      - /library:/media
      - /etc/localtime:/etc/localtime:ro

  open-webui:
    container_name: open-webui
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - ENV=dev  # enable /docs
      - ENABLE_SIGNUP=True
      - DEFAULT_USER_ROLE=admin

      # set model for title generation, web search
      - TASK_MODEL_EXTERNAL=openai/gpt-4o-mini

      # - ENABLE_RAG_WEB_SEARCH=True
      # - RAG_WEB_SEARCH_ENGINE=google_pse

      - RAG_EMBEDDING_MODEL_AUTO_UPDATE=True
      - RAG_RERANKING_MODEL_AUTO_UPDATE=True
      - RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE=True
      - RAG_RERANKING_MODEL_TRUST_REMOTE_CODE=True

      - WHISPER_MODEL=base

      - ENABLE_OLLAMA_API=False

      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - proxynet
    ports:
      - "7000:8080"
    restart: unless-stopped
    volumes:
      - open-webui-data:/app/backend/data

networks:
  proxynet:

volumes:
  vaultwarden-data:
  jellyfin-data:
  open-webui-data:
