services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - proxynet
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs/${TAILSCALE_URL}.crt:/etc/ssl/certs/tailscale.crt:ro
      - ./nginx/certs/${TAILSCALE_URL}.key:/etc/ssl/private/tailscale.key:ro
    environment:
      TAILSCALE_NAME: ${TAILSCALE_NAME}
      TAILSCALE_IP: ${TAILSCALE_IP}
      TAILSCALE_URL: ${TAILSCALE_URL}

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - proxynet
    environment:
      DOMAIN: "https://${TAILSCALE_URL}/vw"
      SIGNUPS_ALLOWED: "false"
      # ADMIN_TOKEN: ""
    volumes:
      - vaultwarden-data:/data/

  jellyfin:
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri  # hardware acceleration
    entrypoint: ["/entrypoint.sh"]
    environment:
      - JELLYFIN_PublishedServerUrl=https://${TAILSCALE_URL}/jellyfin
    image: jellyfin/jellyfin:latest
    networks:
      - proxynet
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - jellyfin-data:/config
      - ./jellyfin/entrypoint.sh:/entrypoint.sh
      - /library:/media
      - /etc/localtime:/etc/localtime:ro

  siren:
    container_name: siren
    build:
      context: https://github.com/kabilan108/siren.git
      dockerfile: Dockerfile.gpu
    restart: always
    networks:
      - proxynet
    environment:
      - SIREN_API_KEY=${SIREN_API_KEY}
    volumes:
      - ${HF_HOME}:/root/.cache/huggingface
    devices:
      - nvidia.com/gpu=all

networks:
  proxynet:

volumes:
  vaultwarden-data:
  jellyfin-data:
  open-webui-data:
