services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - proxynet
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs/${TAILSCALE_URL}.crt:/etc/ssl/certs/tailscale.crt:ro
      - ./nginx/certs/${TAILSCALE_URL}.key:/etc/ssl/private/tailscale.key:ro
    environment:
      TAILSCALE_NAME: ${TAILSCALE_NAME}
      TAILSCALE_IP: ${TAILSCALE_IP}
      TAILSCALE_URL: ${TAILSCALE_URL}

networks:
  proxynet:
