services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000  # Update this to match your user's UID:GID
    network_mode: "host"  # This allows Jellyfin to use the host's network, including Tailscale
    restart: unless-stopped
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - /home/muaddib/docker/jellyfin/config/:/config  # Replace with your desired config location
      - /mnt/media:/media  # Your existing media mount, read-only
      - /etc/localtime:/etc/localtime:ro  # Sync container time with host
      - ./jellyfin/entrypoint.sh:/entrypoint.sh
    devices:
      - /dev/dri:/dev/dri  # Hardware acceleration (if available)
    environment:
      - JELLYFIN_PublishedServerUrl=http://100.104.180.3:8096  # Replace with your Tailscale IP

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "7000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENV=dev  # enable /docs
      - ENABLE_SIGNUP=True
      - DEFAULT_USER_ROLE=admin

      # set model for title generation, web search
      - TASK_MODEL_EXTERNAL=openai/gpt-4o-mini

      # - ENABLE_RAG_WEB_SEARCH=True
      # - RAG_WEB_SEARCH_ENGINE=google_pse

      - RAG_EMBEDDING_MODEL_AUTO_UPDATE=True
      - RAG_RERANKING_MODEL_AUTO_UPDATE=True
      - RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE=True
      - RAG_RERANKING_MODEL_TRUST_REMOTE_CODE=True

      - WHISPER_MODEL=base

      - ENABLE_OLLAMA_API=False

      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always

volumes:
  open-webui:
