[AppSettings]
appMode=0
browseFilters=@Invalid()
defaultJpgQuality=97
firstTime.nomacs.3=false

[DisplaySettings]
bgColorNoMacsRGBA=4279308571
bgColorWidgetRGBA=2852126720
defaultBackgroundColor=false
defaultForegroundColor=false
defaultIconColor=false
fgColorNoMacsRGBA=4291679988
fontColorRGBA=4292730333
highlightColorRGBA=4278216379
iconColorRGBA=4291679988
stylePlugin=fusion
themeName312=Dark-Theme.css
transition=0

[DkDialog]
saveTabsDialog=false
saveTabsDialog-answer=65536

[GlobalSettings]
lastDir=/home/kabilan/media/screenshots
numThreads=-1
recentFolders=/home/kabilan/media/screenshots

[SlideShowSettings]
backgroundColorRGBA=4279308571

[SynchronizeSettings]
checkForUpdates=false
disableUpdateInteraction=false
