model = "gpt-5.4"

model_reasoning_effort = "high"
model_supports_reasoning_summaries = true

sandbox_mode = "workspace-write"

notify = ["/home/kabilan/dotfiles/bin/codex-notify"]
personality = "pragmatic"
service_tier = "fast"

[sandbox_workspace_write]
network_access = true

[shell_environment_policy]
inherit = "all"

[features]
skills = true
unified_exec = true
shell_snapshot = true
steer = true
multi-agent = true

[history]
persistence = "save-all"

[mcp_servers.nixos]
command = "nix"
args = ["run", "github:utensils/mcp-nixos"]
enabled = false

[mcp_servers.exa]
url = "https://sietch.sole-pierce.ts.net/exa-mcp/mcp?tools=web_search_exa,get_code_context_exa,crawling_exa,deep_researcher_start,deep_researcher_check"

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[projects."/vault/repos/OtakuDex"]
trust_level = "trusted"

[projects."/vault/repos/cli/dump"]
trust_level = "trusted"

[projects."/vault/repos/rollouts"]
trust_level = "trusted"

[projects."/home/kabilan/dotfiles"]
trust_level = "trusted"

[projects."/vault/work/moberg/dev-server"]
trust_level = "trusted"

[projects."/vault/repos/cli/atlassian-cli"]
trust_level = "trusted"

[projects."/vault/repos/cli/atlask"]
trust_level = "trusted"

[projects."/vault/work/moberg/dev-server/dashboard"]
trust_level = "trusted"

[projects."/vault/work/moberg/dev-server/moberg-data-query-api"]
trust_level = "trusted"

[projects."/vault/work/moberg/dev-server/python-modules/moberg-signal-processing"]
trust_level = "trusted"

[projects."/vault/work/moberg/dev-server/python-modules/cns-utils"]
trust_level = "trusted"

[projects."/vault/work/moberg/dev-server/utils/git-utils"]
trust_level = "trusted"

[projects."/vault/work/moberg/dev-server/cns-manager"]
trust_level = "trusted"

[projects."/vault/repos/cli/atlas"]
trust_level = "trusted"

[projects."/vault/repos/dictator"]
trust_level = "trusted"

[projects."/vault/repos/nvim-plugins/pyrepl.nvim"]
trust_level = "trusted"

[projects."/vault/experiments/2026-03-10-claude-trippy-bs"]
trust_level = "trusted"

[projects."/vault/experiments/2026-03-06-pingdotgg-t3code"]
trust_level = "trusted"

[projects."/vault/work/moberg/maestro"]
trust_level = "trusted"

[projects."/vault/experiments/2026-03-03-tracer-cli"]
trust_level = "trusted"

[projects."/vault/work/moberg/dev-server/eboost-scripts"]
trust_level = "trusted"
