{
  lib,
  osConfig,
  ...
}:
let
  fleet = import ../../lib/fleet.nix;
  thisHost = osConfig.networking.hostName;
  self = fleet.hosts.${thisHost};
  reachable = lib.filterAttrs (name: _: builtins.elem name self.canAccess) fleet.hosts;

  fleetSshSettings = lib.mapAttrs (name: host: {
    HostName = host.tailscaleIp;
    User = host.user;
    RequestTTY = "yes";
    IdentityFile = [
      "~/.ssh/yk-nfc"
      "~/.ssh/yk-nano"
      "~/.ssh/${name}"
      "~/.ssh/id_ed25519"
    ];
  }) reachable;

  renderHost = name: host: ''
    ## ${name} (${host.role})

    ${host.description}

    - tailnet: `${name}.${fleet.tailnet}` (`${host.tailscaleIp}`)
    - user: `${host.user}`
    - repo roots: ${lib.concatMapStringsSep ", " (r: "`${r}`") host.roots}
    - can ssh into: ${
      if host.canAccess == [ ] then "nothing" else lib.concatStringsSep ", " host.canAccess
    }
    - color: ${host.color.name} (`${host.color.hex}`)
  '';

  computersMd = ''
    # Fleet

    Generated from `lib/fleet.nix` — edit there and rebuild; do not edit this file.
    You are on **${thisHost}**.

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList renderHost fleet.hosts)}

    ## Conventions

    - Reach fleet machines with plain `ssh <name>` (config is generated from the registry).
    - Access is directional: only the `can ssh into` lists above are permitted; never try to reach jacurutu from another machine.
    - Remote interactive work: `ssh <name>` lands in the `main` tmux session automatically; one-off commands (`ssh <name> '<cmd>'`) bypass tmux.
    - Machines are NixOS; config changes go through ~/dotfiles on that machine (`nh os switch` / `nixos-rebuild switch --flake`), never ad-hoc system edits.
  '';
in
{
  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    includes = [ "config.d/private" ];
    settings = fleetSshSettings // {
      "github.com" = {
        User = "git";
        IdentityFile = "~/.ssh/github";
      };
      "bitbucket.org" = {
        User = "git";
        IdentityFile = "~/.ssh/moberg-bitbucket";
      };
    };
  };

  home.sessionVariables = {
    FLEET_HOST_ANSI = self.color.ansi;
    FLEET_HOST_HEX = self.color.hex;
  };

  home.file.".config/tmux/host.conf".text = ''
    set -g @host_color '${self.color.hex}'
    set -g pane-active-border-style 'fg=${self.color.hex}'
    set -g status-right '#[fg=#{@thm_yellow},bg=default]#{?client_prefix,PREFIX ,}#{?pane_in_mode,COPY ,}#{?window_zoomed_flag,ZOOM ,}#[bg=default] #[fg=#{@thm_crust},bg=${self.color.hex},bold] #S #[fg=${self.color.hex},bg=#{@thm_surface_0}] 󰒋 ${thisHost} '
  '';

  home.file.".config/fleet/computers.md".text = computersMd;
}
