{
  lib,
  osConfig,
  ...
}:
let
  fleet = import ../../lib/fleet.nix;
  thisHost = osConfig.networking.hostName;
  self = fleet.hosts.${thisHost};
  reachable = lib.filterAttrs (name: _: builtins.elem name self.canAccess) fleet.hosts;

  fleetSshSettings = lib.mapAttrs (name: host: {
    HostName = host.tailscaleIp;
    User = host.user;
    RequestTTY = "yes";
    IdentityFile = [
      "~/.ssh/yk-nfc"
      "~/.ssh/yk-nano"
      "~/.ssh/${name}"
      "~/.ssh/id_ed25519"
    ];
    # without this, ssh also offers every key the desktop ssh-agent holds -
    # including the passwordless agent-<host> key, silently bypassing the
    # hardware-key requirement for human logins
    IdentitiesOnly = "yes";
    ControlMaster = "auto";
    ControlPath = "~/.ssh/cm-%r@%h-%p";
    ControlPersist = "4h";
  }) reachable;

  # non-interactive identities for agents/scripts: never touch the YubiKey,
  # never prompt, authenticate with this machine's restricted agent key
  agentSshSettings = lib.mapAttrs' (
    name: host:
    lib.nameValuePair "${name}-agent" {
      HostName = host.tailscaleIp;
      User = host.user;
      IdentityFile = "~/.ssh/agent-${thisHost}";
      IdentitiesOnly = "yes";
      BatchMode = "yes";
    }
  ) reachable;

  renderHost = name: host: ''
    ## ${name} (${host.role})

    ${host.description}

    - tailnet: `${name}.${fleet.tailnet}` (`${host.tailscaleIp}`)
    - user: `${host.user}`
    - repo roots: ${lib.concatMapStringsSep ", " (r: "`${r}`") host.roots}
    - can ssh into: ${
      if host.canAccess == [ ] then "nothing" else lib.concatStringsSep ", " host.canAccess
    }
    - color: ${host.color.name} (`${host.color.hex}`)
  '';

  computersMd = ''
    # Fleet

    Generated from `lib/fleet.nix` — edit there and rebuild; do not edit this file.
    You are on **${thisHost}**.

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList renderHost fleet.hosts)}

    ## Conventions

    - Agents/scripts reach fleet machines with `ssh <name>-agent` (restricted key, BatchMode, no prompts); plain `ssh <name>` is the human path (hardware key + tmux auto-attach).
    - From a remote tmux view: `M-d` jumps back to the local machine's session picker; plain detach (prefix+d) returns to the session you came from.
    - Access is directional: only the `can ssh into` lists above are permitted; never try to reach jacurutu from another machine.
    - Remote interactive work: `ssh <name>` lands in the `main` tmux session automatically; one-off commands (`ssh <name> '<cmd>'`) bypass tmux.
    - Machines are NixOS; config changes go through ~/dotfiles on that machine (`nh os switch` / `nixos-rebuild switch --flake`), never ad-hoc system edits.
  '';
in
{
  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    includes = [ "config.d/private" ];
    settings =
      fleetSshSettings
      // agentSshSettings
      // {
        "github.com" = {
          User = "git";
          IdentityFile = "~/.ssh/github";
        };
        "bitbucket.org" = {
          User = "git";
          IdentityFile = "~/.ssh/moberg-bitbucket";
        };
      };
  };

  # Materialize ~/.ssh/config as a real user-owned file instead of a
  # nix-store symlink: agent harness shells see the store through an
  # id-mapped mount (files stat as nobody), and ssh rejects a config it
  # thinks isn't owned by the user ("Bad owner or permissions").
  home.file.".ssh/config" = {
    target = lib.mkForce ".ssh/config_source";
    onChange = ''
      cat "$HOME/.ssh/config_source" > "$HOME/.ssh/config"
      chmod 400 "$HOME/.ssh/config"
    '';
  };

  home.sessionVariables = {
    FLEET_HOST_ANSI = self.color.ansi;
    FLEET_HOST_HEX = self.color.hex;
  };

  home.file.".config/tmux/host.conf".text = ''
    set -g @host_color '${self.color.hex}'
    set -g pane-active-border-style 'fg=${self.color.hex}'
    set -g status-right '#[fg=#{@thm_yellow},bg=default]#{?client_prefix,PREFIX ,}#{?pane_in_mode,COPY ,}#{?window_zoomed_flag,ZOOM ,}#[bg=default] #[fg=#{@thm_crust},bg=${self.color.hex},bold] #S #[fg=${self.color.hex},bg=#{@thm_surface_0}] 󰒋 ${thisHost} '
  ''
  + lib.optionalString (self.role != "control-plane") ''
    # exit 42 tells the connecting machine's sessionizer chain to reopen
    # its local picker (jump home) instead of re-attaching the origin
    bind -n M-d detach-client -E 'exit 42'
  '';

  home.file.".config/fleet/computers.md".text = computersMd;

  home.file.".config/fleet/hosts".text =
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: host: "${name}\t${host.color.hex}\t${host.tailscaleIp}") reachable
    )
    + "\n";
}
