;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;      ____        __      __
;     / __ \____  / __  __/ /_  ____ ______
;    / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;   / ____/ /_/ / / /_/ / /_/ / /_/ / /
;  /_/    \____/_/\__, /_.___/\__,_/_/
;                /____/
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[global/wm]
include-file = $HOME/.config/polybar/colors.ini

[settings]
screenchange-reload = true
pseudo-transparency = false

[bar/main]
width = 100%
height = 25pt
radius = 10
fixed-center = true
background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt
border-top = 4
border-left = 4
border-right = 4
border-bottom = 2pt

padding-left = 1
padding-right = 1
module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "FiraMono Nerd Font:size=12;4"
font-1 = "FiraMono Nerd Font:size=12;4"

cursor-click = pointer

enable-ipc = true
monitor = ${env:MONITOR}

modules-left = menu xworkspaces xwindow
modules-center = date
modules-right = pulseaudio memory cpu battery systray

[module/menu]
type = custom/text
format = " "
format-foreground = ${colors.peach}
content-padding = 1
click-left = rofi -show combi
click-right = $HOME/.config/rofi/menus/exit

[module/systray]
type = internal/tray
tray-size = 20

[module/xworkspaces]
type = internal/xworkspaces

pin-workspaces = true
show-urgent = true
index-sort = true

enable-click = true

enable-scroll = true
wrapping-scroll = true
reverse-scroll = false
fuzzy-match = true

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-foreground = ${colors.base}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume>  <label-volume>

label-volume = %percentage%%
label-volume-foreground = ${colors.teal}

label-muted = "󰝟 "
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-4 = 
ramp-volume-5 = 
ramp-volume-6 = 
ramp-volume-foreground = ${colors.teal}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.rosewater}
label = %percentage_used:2%%
label-foreground = ${colors.rosewater}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.yellow}
label = %percentage:2%%
label-foreground = ${colors.yellow}

[module/date]
type = internal/date
interval = 1

date = %m-%d-%Y %H:%M:%S
date-alt = %H:%M

label = %date%
label-foreground = ${colors.primary}

[module/battery]
type = internal/battery
battery = BAT1
adapter = AC
full-at = 90

format-charging = <animation-charging> <label-charging>
format-charging-foreground = ${colors.green}
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-foreground = ${colors.flamingo}
format-full = <ramp-capacity> <label-full>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = Full

ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁻
ramp-capacity-2 = 󰁼
ramp-capacity-3 = 󰁽
ramp-capacity-4 = 󰁾
ramp-capacity-5 = 󰁿
ramp-capacity-6 = 󰂀
ramp-capacity-7 = 󰂁
ramp-capacity-8 = 󰂂
ramp-capacity-9 = 󰁹

animation-charging-0 = 󰢜
animation-charging-1 = 󰂆
animation-charging-2 = 󰂇
animation-charging-3 = 󰂈
animation-charging-4 = 󰢝
animation-charging-framerate = 750

; vim:ft=dosini
