#! /bin/bash

file_path=$(realpath "$1")

if [ ! -e "$file_path" ]; then
  echo "Error: File or directory not found" >&2
  exit 1
fi

absolute_path=$(realpath "$file_path")
encoded_path=$(printf '%s' "$absolute_path" | sed 's/[^a-zA-Z0-9]/\\&/g; s/\\//g')
echo "file://$encoded_path"
